name: YangBaxter
version: 0.2.0
date: 2018-04-13
description: |
    Combinatorial Solutions for the Yang-Baxter equation

authors:
    - name: Leandro Vendramin
      url: http://mate.dm.uba.ar/~lvendram
    - name: Alexander Konovalov
      url: http://www.cs.st-andrews.ac.uk/~alexk/

maintainers:
    - name: Leandro Vendramin
      url: http://mate.dm.uba.ar/~lvendram
    - name: Alexander Konovalov
      url: http://www.cs.st-andrews.ac.uk/~alexk/

GAP: ">=4.8"

www: https://gap-packages.github.io/YangBaxter
readme: README.md
packageinfo: https://gap-packages.github.io/YangBaxter/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/YangBaxter/releases/download/v0.2.0/YangBaxter-0.2.0.tar.gz

abstract: |
    The <span class="pkgname">YangBaxter</span> package provides functionality to construct classical and skew braces. It also includes a database of classical and skew braces of small orders.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
