name: YangBaxter
version: 0.8.0
date: 2019-08-02
description: |
    Combinatorial Solutions for the Yang-Baxter equation

authors:
    - name: Leandro Vendramin
      url: http://mate.dm.uba.ar/~lvendram
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Leandro Vendramin
      url: http://mate.dm.uba.ar/~lvendram
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk/

GAP: ">=4.9"

www: https://gap-packages.github.io/YangBaxter
readme: README.md
packageinfo: https://gap-packages.github.io/YangBaxter/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/YangBaxter/releases/download/v0.8.0/YangBaxter-0.8.0.tar.gz

abstract: |
    The <span class="pkgname">YangBaxter</span> package provides functionality to construct classical and skew braces. It also includes a database of classical and skew braces of small orders.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
